#! /usr/bin/env python

import rospy

from bwi_coffee import PlannerCoffee

if __name__ == '__main__':
    try:
        rospy.init_node('planner_coffee')
        client = PlannerCoffee()
        client.start()
    except rospy.ROSInterruptException:
        rospy.logwarn("Planner interrupted before completeion!")


