#! /usr/bin/env python

import rospy

from bwi_coffee_new import PlannerCoffeeNew

if __name__ == '__main__':
    try:
        rospy.init_node('planner_coffee_new')
        client = PlannerCoffeeNew()
        client.start()
    except rospy.ROSInterruptException:
        rospy.logwarn("Planner interrupted before completeion!")


